-- Which community areas have the most crime?

SELECT COMMUNITY_AREA_NAME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER IN
(
    SELECT COMMUNITY_AREA_NUMBER
    FROM CRIME_DATA
    GROUP BY COMMUNITY_AREA_NUMBER
    ORDER BY COUNT(*) DESC
    LIMIT 5
);


-- Which community areas have the least crime?

SELECT COMMUNITY_AREA_NAME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER IN
(
    SELECT COMMUNITY_AREA_NUMBER
    FROM CRIME_DATA
    GROUP BY COMMUNITY_AREA_NUMBER
    ORDER BY COUNT(*) ASC
    LIMIT 5
);

-- Per capita income for community with the highest crime rates

SELECT COMMUNITY_AREA_NAME, PER_CAPITA_INCOME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER IN
(
    SELECT COMMUNITY_AREA_NUMBER
    FROM CRIME_DATA
    GROUP BY COMMUNITY_AREA_NUMBER
    ORDER BY COUNT(*) DESC
    LIMIT 1
);

-- Per capita income for community with the lowest crime rates

SELECT COMMUNITY_AREA_NAME, PER_CAPITA_INCOME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER IN
(
    SELECT COMMUNITY_AREA_NUMBER
    FROM CRIME_DATA
    GROUP BY COMMUNITY_AREA_NUMBER
    ORDER BY COUNT(*) ASC
    LIMIT 1
);

-- Percentage of crimes that are theft or battery
SELECT 
    (SELECT COUNT(*) 
     FROM CRIME_DATA 
     WHERE PRIMARY_TYPE IN ('THEFT', 'BATTERY')) * 100.0
    /
    (SELECT COUNT(*) 
     FROM CRIME_DATA) 
AS percentage_theft_battery;





