-- Which community areas have the most crime?

SELECT COMMUNITY_AREA_NAME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER IN
(
    SELECT COMMUNITY_AREA_NUMBER
    FROM CRIME_DATA
    GROUP BY COMMUNITY_AREA_NUMBER
    ORDER BY COUNT(*) DESC
    LIMIT 5
);


-- Which community areas have the least crime?

SELECT COMMUNITY_AREA_NAME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER IN
(
    SELECT COMMUNITY_AREA_NUMBER
    FROM CRIME_DATA
    GROUP BY COMMUNITY_AREA_NUMBER
    ORDER BY COUNT(*) ASC
    LIMIT 5
);

-- Per capita income for community with the highest crime rates

SELECT COMMUNITY_AREA_NAME, PER_CAPITA_INCOME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER IN
(
    SELECT COMMUNITY_AREA_NUMBER
    FROM CRIME_DATA
    GROUP BY COMMUNITY_AREA_NUMBER
    ORDER BY COUNT(*) DESC
    LIMIT 1
);

-- Per capita income for community with the highest crime rates

SELECT COMMUNITY_AREA_NAME, PER_CAPITA_INCOME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER IN
(
    SELECT COMMUNITY_AREA_NUMBER
    FROM CRIME_DATA
    GROUP BY COMMUNITY_AREA_NUMBER
    ORDER BY COUNT(*) ASC
    LIMIT 1
);





